---
# Kubernetes Job for initializing databases from backups
# Restores MariaDB and MongoDB from backup files
# 
# IMPORTANT: This script assumes backup files are accessible from the host.
# Run this from a machine with kubectl access to the cluster.
# Backup files should be at: caritas-workspace/ORISO-Database/backups/{timestamp}/
apiVersion: batch/v1
kind: Job
metadata:
  name: database-initialize
  namespace: caritas
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: database-initialize
    spec:
      restartPolicy: OnFailure
      serviceAccountName: database-initialize-job
      containers:
      - name: initialize-databases
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          # Get configuration from ConfigMap
          NAMESPACE=$(kubectl get configmap database-initialize-config -n caritas -o jsonpath='{.data.namespace}' || echo "caritas")
          BACKUP_TIMESTAMP=$(kubectl get configmap database-initialize-config -n $NAMESPACE -o jsonpath='{.data.backupTimestamp}')
          
          if [ -z "$BACKUP_TIMESTAMP" ]; then
            echo "ERROR: backupTimestamp not found in ConfigMap"
            exit 1
          fi
          
          echo "Initializing databases from backup: $BACKUP_TIMESTAMP"
          
          # Wait for MariaDB pod
          echo "Waiting for MariaDB pod..."
          MARIADB_POD=""
          for i in $(seq 1 30); do
            MARIADB_POD=$(kubectl get pods -n $NAMESPACE -l app=mariadb -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")
            if [ -n "$MARIADB_POD" ]; then
              READY=$(kubectl get pod -n $NAMESPACE $MARIADB_POD -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "False")
              if [ "$READY" = "True" ]; then
                break
              fi
            fi
            sleep 2
          done
          
          if [ -z "$MARIADB_POD" ]; then
            echo "ERROR: MariaDB pod not found or not ready"
            exit 1
          fi
          
          echo "Found MariaDB pod: $MARIADB_POD"
          
          # Get MariaDB root password
          MARIADB_ROOT_PASS=$(kubectl get secret mariadb-secrets -n $NAMESPACE -o jsonpath='{.data.MYSQL_ROOT_PASSWORD}' 2>/dev/null | base64 -d || echo "root")
          
          # Restore MariaDB from backup
          # Note: Backup file must be copied to this pod first using: kubectl cp <backup-path> caritas/<pod-name>:/tmp/mariadb-backup.sql.gz
          echo "Restoring MariaDB from backup..."
          
          if [ ! -f "/tmp/mariadb-backup.sql.gz" ]; then
            echo "ERROR: MariaDB backup file not found at /tmp/mariadb-backup.sql.gz"
            echo "Please copy the backup file to this pod first using:"
            echo "  kubectl cp <backup-path> $NAMESPACE/$(hostname):/tmp/mariadb-backup.sql.gz"
            exit 1
          fi
          
          echo "Restoring MariaDB..."
          gunzip -c /tmp/mariadb-backup.sql.gz | kubectl exec -i -n $NAMESPACE $MARIADB_POD -- mysql -u root -p"$MARIADB_ROOT_PASS"
          
          if [ $? -eq 0 ]; then
            echo "✓ MariaDB restored successfully"
          else
            echo "✗ MariaDB restore failed"
            exit 1
          fi
          
          # Wait for MongoDB pod
          echo "Waiting for MongoDB pod..."
          MONGODB_POD=""
          for i in $(seq 1 30); do
            MONGODB_POD=$(kubectl get pods -n $NAMESPACE -l app=mongodb -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")
            if [ -n "$MONGODB_POD" ]; then
              READY=$(kubectl get pod -n $NAMESPACE $MONGODB_POD -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "False")
              if [ "$READY" = "True" ]; then
                break
              fi
            fi
            sleep 2
          done
          
          if [ -z "$MONGODB_POD" ]; then
            echo "ERROR: MongoDB pod not found or not ready"
            exit 1
          fi
          
          echo "Found MongoDB pod: $MONGODB_POD"
          
          # Restore MongoDB from backup
          # Note: Backup file must be copied to this pod first using: kubectl cp <backup-path> caritas/<pod-name>:/tmp/mongodb-backup.archive.gz
          echo "Restoring MongoDB from backup..."
          
          if [ ! -f "/tmp/mongodb-backup.archive.gz" ]; then
            echo "ERROR: MongoDB backup file not found at /tmp/mongodb-backup.archive.gz"
            echo "Please copy the backup file to this pod first using:"
            echo "  kubectl cp <backup-path> $NAMESPACE/$(hostname):/tmp/mongodb-backup.archive.gz"
            exit 1
          fi
          
          echo "Copying backup to MongoDB pod..."
          kubectl cp /tmp/mongodb-backup.archive.gz $NAMESPACE/$MONGODB_POD:/tmp/mongodb-backup.archive.gz
          
          echo "Restoring MongoDB..."
          kubectl exec -n $NAMESPACE $MONGODB_POD -- mongorestore --archive --gzip /tmp/mongodb-backup.archive.gz
          
          if [ $? -eq 0 ]; then
            echo "✓ MongoDB restored successfully"
          else
            echo "✗ MongoDB restore failed"
            exit 1
          fi
          
          echo "✅ Database initialization completed"
---
# ConfigMap for database initialization configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-initialize-config
  namespace: caritas
data:
  namespace: "caritas"
  backupTimestamp: "20251227_084654"
---
# ServiceAccount for the Job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-initialize-job
  namespace: caritas
---
# Role with required permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: database-initialize-job
  namespace: caritas
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: database-initialize-job
  namespace: caritas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: database-initialize-job
subjects:
- kind: ServiceAccount
  name: database-initialize-job
  namespace: caritas
